#!/usr/bin/env node
// embed_ffx.js — re-embed pseudo-effect .ffx binaries into their .jsx files
//
// Reads the binary .ffx, encodes every byte as a \xHH escape sequence,
// chunks the result into readable lines, and rewrites the embedded
// constant inside the target .jsx between // EMBED:BEGIN <slug> and
// // EMBED:END <slug> markers.
//
// Run after editing any .ffx (in Pseudo Effect Maker, via Animation
// Preset save, etc.). Both .ffx and .jsx files should then be committed
// together.
//
// Usage:
//   node tools/embed_ffx.js              # embeds all targets
//   node tools/embed_ffx.js handoff      # embeds only the handoff target
//
// Output:
//   - Updates each target .jsx in place
//   - Prints byte count, chunk count, and final .jsx size per target

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

const TARGETS = [
    {
        slug:        'handoff',
        ffxPath:     path.join(ROOT, 'handoff', 'Handoff.ffx'),
        jsxPath:     path.join(ROOT, 'handoff', 'Handoff.jsx'),
        markerSlug:  'handoff_ffx_binary',
        constName:   'HANDOFF_FFX_BINARY',
        sourceLabel: 'handoff/Handoff.ffx',
        cepAssetsDir: path.join(ROOT, 'handoff', 'cep', 'com.aetools.handoff', 'assets'),
        cepFfxName:   'Handoff.ffx'
    },
    {
        slug:        'vgallery',
        ffxPath:     path.join(ROOT, 'vGallery', 'vGallery.ffx'),
        jsxPath:     path.join(ROOT, 'vGallery', 'vGalleryRig.jsx'),
        markerSlug:  'vgallery_ffx_binary',
        constName:   'VGALLERY_FFX_BINARY',
        sourceLabel: 'vGallery/vGallery.ffx'
    }
];

const CHUNK_BYTES = 32; // bytes per source line — keeps the .jsx readable

function encodeBytes(buf) {
    const lines = [];
    for (let i = 0; i < buf.length; i += CHUNK_BYTES) {
        const slice = buf.slice(i, i + CHUNK_BYTES);
        let s = '';
        for (let j = 0; j < slice.length; j++) {
            const b = slice[j];
            s += '\\x' + (b < 16 ? '0' : '') + b.toString(16).toUpperCase();
        }
        lines.push('        "' + s + '"');
    }
    return lines.join(' +\n');
}

function buildBlock(target, buf) {
    const begin = '// EMBED:BEGIN ' + target.markerSlug;
    const end   = '// EMBED:END '   + target.markerSlug;
    return [
        begin,
        '    // ' + buf.length + ' bytes — generated by tools/embed_ffx.js from ' + target.sourceLabel,
        '    // Do NOT edit this block by hand. Edit the .ffx and re-run',
        '    // `node tools/embed_ffx.js` to refresh.',
        '    var ' + target.constName + ' =',
        encodeBytes(buf) + ';',
        '    ' + end
    ].join('\n');
}

function embedTarget(target) {
    if (!fs.existsSync(target.ffxPath)) {
        console.error('SKIP ' + target.slug + ': .ffx not found at ' + target.ffxPath);
        return false;
    }
    if (!fs.existsSync(target.jsxPath)) {
        console.error('SKIP ' + target.slug + ': .jsx not found at ' + target.jsxPath);
        return false;
    }

    const begin = '// EMBED:BEGIN ' + target.markerSlug;
    const end   = '// EMBED:END '   + target.markerSlug;

    const ffxBytes = fs.readFileSync(target.ffxPath);
    const jsxText  = fs.readFileSync(target.jsxPath, 'utf8');

    const beginIdx = jsxText.indexOf(begin);
    const endIdx   = jsxText.indexOf(end);

    if (beginIdx === -1 || endIdx === -1) {
        console.error(
            'ERROR ' + target.slug + ': could not find embed markers in ' +
            path.relative(ROOT, target.jsxPath) + '.\n' +
            '  Expected: ' + begin + ' ... ' + end
        );
        return false;
    }

    let lineStart = beginIdx;
    while (lineStart > 0 && jsxText[lineStart - 1] !== '\n') lineStart--;

    let lineEnd = endIdx + end.length;
    while (lineEnd < jsxText.length && jsxText[lineEnd] !== '\n') lineEnd++;

    const indent = jsxText.slice(lineStart, beginIdx);
    const newBlock = buildBlock(target, ffxBytes)
        .split('\n')
        .map((ln, i) => (i === 0 ? indent + ln : ln))
        .join('\n');

    const newJsx = jsxText.slice(0, lineStart) + newBlock + jsxText.slice(lineEnd);
    fs.writeFileSync(target.jsxPath, newJsx);

    const chunkLines = encodeBytes(ffxBytes).split('\n').length;
    console.log('Embedded ' + ffxBytes.length + ' bytes (' + target.slug + ') into ' +
                path.relative(ROOT, target.jsxPath));
    console.log('  ' + chunkLines + ' chunk lines, ' + CHUNK_BYTES + ' bytes per chunk');
    console.log('  Final .jsx size: ' + fs.statSync(target.jsxPath).size + ' bytes');

    if (target.cepAssetsDir && target.cepFfxName) {
        const cepFfx = path.join(target.cepAssetsDir, target.cepFfxName);
        if (fs.existsSync(target.cepAssetsDir)) {
            fs.copyFileSync(target.ffxPath, cepFfx);
            console.log('  Copied to ' + path.relative(ROOT, cepFfx));
        }
    }
    return true;
}

function main() {
    const filter = process.argv[2];
    const list = filter
        ? TARGETS.filter(t => t.slug === filter)
        : TARGETS;
    if (list.length === 0) {
        console.error('No targets matched. Available: ' + TARGETS.map(t => t.slug).join(', '));
        process.exit(1);
    }
    let any = false;
    for (const t of list) {
        if (embedTarget(t)) any = true;
    }
    if (!any) process.exit(1);
}

main();
